/**
 * Per-category configuration for the 16 supported business categories:
 * lead-qualification questions, default service menus (prices in paise),
 * content-template hints and AI tone guidance.
 *
 * MUST stay in sync with apps/api/app/modules/profiles/categories.py —
 * a key or content mismatch causes silent validation failures.
 */

import type { BusinessCategory } from "./index";

export interface CategoryConfig {
  key: BusinessCategory;
  displayName: string;
  emoji: string;
  description: string;
  /** How fast leads go cold in this category. */
  urgencyLevel: "high" | "medium" | "low";
  pricingType: "package" | "per_job" | "hourly" | "subscription" | "quote";
  /** Ordered questions the AI asks a new lead before quoting. */
  qualificationQuestions: string[];
  /** Realistic tier-1/2 Indian city price ranges, in paise (₹1 = 100 paise). */
  defaultServices: Array<{
    name: string;
    priceMinPaise: number;
    priceMaxPaise: number;
    unit: string;
  }>;
  suggestedDiscountPolicy: string;
  templateStyle: string;
  /** Style guidance passed to NanoBanana Pro image generation. */
  imageStyleNotes: string;
  /** How the AI should talk to leads in this category. */
  aiToneNotes: string;
}

export const CATEGORIES: Record<BusinessCategory, CategoryConfig> = {
  home_cleaning: {
    key: "home_cleaning",
    displayName: "Home Cleaning",
    emoji: "🧹",
    description: "Professional deep and regular cleaning for homes and apartments.",
    urgencyLevel: "medium",
    pricingType: "per_job",
    qualificationQuestions: [
      "What size is your home — 1BHK, 2BHK, 3BHK or a villa?",
      "Do you need a deep clean, regular clean, or move-in/move-out cleaning?",
      "Which area and pin code is the home in?",
      "Is the home currently occupied or vacant?",
      "Any pets at home, or specific areas needing extra attention like kitchen or balconies?",
      "What date and time slot works best for you?",
    ],
    defaultServices: [
      { name: "Deep cleaning — 1BHK", priceMinPaise: 180000, priceMaxPaise: 300000, unit: "per 1BHK" },
      { name: "Deep cleaning — 2BHK", priceMinPaise: 250000, priceMaxPaise: 450000, unit: "per 2BHK" },
      { name: "Deep cleaning — 3BHK", priceMinPaise: 350000, priceMaxPaise: 600000, unit: "per 3BHK" },
      { name: "Sofa shampooing", priceMinPaise: 25000, priceMaxPaise: 50000, unit: "per seat" },
      { name: "Bathroom deep clean", priceMinPaise: 45000, priceMaxPaise: 80000, unit: "per bathroom" },
    ],
    suggestedDiscountPolicy: "10% off the first booking; 15% off on quarterly deep-clean subscriptions.",
    templateStyle: "before/after grid",
    imageStyleNotes: "Bright, airy interiors with visible before/after contrast; sparkling tiles and sunlight through windows. Clean whites and fresh blues, uniformed staff with branded equipment.",
    aiToneNotes: "Warm and reassuring; emphasise trained, background-verified staff and safe chemicals. Confirm size and date quickly and offer a firm slot.",
  },
  plumbing: {
    key: "plumbing",
    displayName: "Plumbing Services",
    emoji: "🔧",
    description: "Repairs, fittings and full bathroom plumbing work for homes and offices.",
    urgencyLevel: "high",
    pricingType: "per_job",
    qualificationQuestions: [
      "What's the issue — a leak, blockage, low pressure, or a new fitting/installation?",
      "Which area and pin code should the plumber come to?",
      "How urgent is it — is water leaking or overflowing right now?",
      "Can you share a photo or short video of the problem?",
      "Is it an apartment or independent house, and which floor?",
    ],
    defaultServices: [
      { name: "Tap/faucet repair or replacement", priceMinPaise: 15000, priceMaxPaise: 50000, unit: "per fitting" },
      { name: "Drain/blockage clearing", priceMinPaise: 30000, priceMaxPaise: 150000, unit: "per job" },
      { name: "Bathroom leakage detection & fix", priceMinPaise: 50000, priceMaxPaise: 250000, unit: "per job" },
      { name: "Wash basin/sanitaryware installation", priceMinPaise: 40000, priceMaxPaise: 120000, unit: "per unit" },
      { name: "Full bathroom plumbing renovation", priceMinPaise: 800000, priceMaxPaise: 2500000, unit: "per bathroom" },
    ],
    suggestedDiscountPolicy: "10% off scheduled repair visits; no discounts on emergency call-outs.",
    templateStyle: "problem/solution card",
    imageStyleNotes: "Close-up shots of gleaming chrome fittings and tidy pipe work; a professional in uniform with a toolbox. Blue and steel-grey palette, crisp and trustworthy.",
    aiToneNotes: "Fast, calm and practical — for emergencies, get the address and dispatch details first, pricing second. Reassure about visiting charges being adjusted in the bill.",
  },
  electrical: {
    key: "electrical",
    displayName: "Electrical Services",
    emoji: "⚡",
    description: "Licensed electricians for repairs, installations and wiring work.",
    urgencyLevel: "high",
    pricingType: "per_job",
    qualificationQuestions: [
      "What's the problem — no power, tripping MCB, sparking, or a new installation?",
      "Is the issue in one room or the whole house?",
      "Which area and pin code should the electrician come to?",
      "Is there any sparking, burning smell or exposed wiring right now?",
      "Is it an apartment or independent house, and roughly how old is the wiring?",
    ],
    defaultServices: [
      { name: "Switch/socket repair or replacement", priceMinPaise: 10000, priceMaxPaise: 35000, unit: "per point" },
      { name: "Ceiling fan installation", priceMinPaise: 25000, priceMaxPaise: 60000, unit: "per fan" },
      { name: "Inverter installation", priceMinPaise: 80000, priceMaxPaise: 200000, unit: "per unit" },
      { name: "MCB/distribution board repair", priceMinPaise: 40000, priceMaxPaise: 150000, unit: "per job" },
      { name: "Full house rewiring — 1BHK", priceMinPaise: 1500000, priceMaxPaise: 4000000, unit: "per 1BHK" },
    ],
    suggestedDiscountPolicy: "Free inspection with any repair above ₹500; no discounts on emergency visits.",
    templateStyle: "safety-tip carousel",
    imageStyleNotes: "Neat switchboards, organised wiring and an electrician with insulated tools; warm indoor lighting. Yellow-and-black safety accents without looking industrial.",
    aiToneNotes: "Safety-first and urgent — if sparking or burning smell is mentioned, advise switching off the mains and prioritise dispatch. Keep questions short and sequential.",
  },
  wedding_photography: {
    key: "wedding_photography",
    displayName: "Wedding Photography",
    emoji: "📸",
    description: "Candid and traditional wedding photography and films across events.",
    urgencyLevel: "medium",
    pricingType: "package",
    qualificationQuestions: [
      "What's the wedding date and city?",
      "Is the venue finalised — if yes, which one?",
      "Which events do you want covered — haldi, mehendi, sangeet, wedding, reception?",
      "Do you want candid photography, traditional, or both — and do you also need video/cinematic film?",
      "Roughly how many guests are expected at the main functions?",
      "What budget range are you considering for photography?",
    ],
    defaultServices: [
      { name: "Single-day wedding shoot (candid + traditional)", priceMinPaise: 4000000, priceMaxPaise: 10000000, unit: "per day" },
      { name: "Full wedding package — 3 events, photo + video", priceMinPaise: 12000000, priceMaxPaise: 35000000, unit: "per package" },
      { name: "Pre-wedding shoot", priceMinPaise: 1500000, priceMaxPaise: 5000000, unit: "per shoot" },
      { name: "Cinematic wedding film add-on", priceMinPaise: 5000000, priceMaxPaise: 15000000, unit: "per film" },
      { name: "Premium wedding album", priceMinPaise: 800000, priceMaxPaise: 2500000, unit: "per album" },
    ],
    suggestedDiscountPolicy: "5-10% off on full multi-event packages booked 6+ months in advance; no discounts on single-day peak-season dates.",
    templateStyle: "cinematic photo carousel",
    imageStyleNotes: "Rich, golden-hour candid wedding moments — varmala, sangeet dance, emotional family shots. Warm tones, shallow depth of field, Indian bridal reds and golds.",
    aiToneNotes: "Emotive and consultative — congratulate the couple first, then gather date and events. Emphasise limited dates per season to create gentle urgency.",
  },
  interior_design: {
    key: "interior_design",
    displayName: "Interior Design",
    emoji: "🛋️",
    description: "End-to-end home and office interiors, from design to execution.",
    urgencyLevel: "low",
    pricingType: "quote",
    qualificationQuestions: [
      "What's the property — 2BHK, 3BHK, villa or office — and the carpet area?",
      "Which city and locality is the project in?",
      "Do you want full-home interiors or specific rooms like kitchen and wardrobes?",
      "Have you received possession, and what's your target completion timeline?",
      "Any style preference — modern, minimal, traditional, or something you've saved on Instagram?",
      "What budget band are you planning — under ₹5L, ₹5-10L, ₹10-20L, or above?",
    ],
    defaultServices: [
      { name: "Design consultation & 3D concept", priceMinPaise: 200000, priceMaxPaise: 500000, unit: "per visit" },
      { name: "Modular kitchen", priceMinPaise: 12000000, priceMaxPaise: 35000000, unit: "per kitchen" },
      { name: "Full 2BHK interiors", priceMinPaise: 40000000, priceMaxPaise: 90000000, unit: "per 2BHK" },
      { name: "Full 3BHK interiors", priceMinPaise: 65000000, priceMaxPaise: 150000000, unit: "per 3BHK" },
      { name: "Sliding/hinged wardrobe", priceMinPaise: 4000000, priceMaxPaise: 12000000, unit: "per wardrobe" },
    ],
    suggestedDiscountPolicy: "Consultation fee fully adjusted against the project value on booking; no flat discounts on materials.",
    templateStyle: "room transformation reel",
    imageStyleNotes: "Magazine-quality wide shots of finished Indian living rooms and modular kitchens; warm woods, brass accents, layered lighting. Aspirational but achievable, not palatial.",
    aiToneNotes: "Consultative and unhurried — this is a big-ticket decision, so focus on understanding scope and budget band before talking numbers. Offer a free/adjustable design consultation as the next step.",
  },
  personal_training: {
    key: "personal_training",
    displayName: "Personal Training",
    emoji: "💪",
    description: "Certified personal trainers for home, gym and online fitness coaching.",
    urgencyLevel: "medium",
    pricingType: "subscription",
    qualificationQuestions: [
      "What's your main goal — weight loss, muscle gain, strength, or general fitness?",
      "Do you prefer training at home, at a gym, or online?",
      "Which area and pin code are you in, if you want home sessions?",
      "What's your current activity level, and any injuries or health conditions I should know about?",
      "How many sessions per week are you planning, and what time slot suits you?",
    ],
    defaultServices: [
      { name: "Monthly PT — 3 sessions/week (home)", priceMinPaise: 600000, priceMaxPaise: 1200000, unit: "per month" },
      { name: "Monthly PT — 5 sessions/week (home)", priceMinPaise: 900000, priceMaxPaise: 1800000, unit: "per month" },
      { name: "Online coaching plan", priceMinPaise: 300000, priceMaxPaise: 700000, unit: "per month" },
      { name: "Trial session", priceMinPaise: 50000, priceMaxPaise: 100000, unit: "per session" },
      { name: "Customised diet + workout plan", priceMinPaise: 200000, priceMaxPaise: 500000, unit: "per plan" },
    ],
    suggestedDiscountPolicy: "Trial session fee adjusted in the first month; 10% off on quarterly prepaid plans.",
    templateStyle: "client transformation spotlight",
    imageStyleNotes: "Energetic training moments and authentic client transformation collages; natural gym or home-workout lighting. Bold typography for stats like weight lost or strength gained.",
    aiToneNotes: "Motivating but not pushy — acknowledge the goal, ask about injuries sensitively, and push the low-commitment trial session as the first step.",
  },
  salon_beauty: {
    key: "salon_beauty",
    displayName: "Salon & Beauty",
    emoji: "💇",
    description: "Salon services, skincare and bridal makeup — in-salon or at home.",
    urgencyLevel: "medium",
    pricingType: "per_job",
    qualificationQuestions: [
      "Which services are you looking for — hair, facial, waxing, makeup, or a combination?",
      "Would you like to visit the salon or prefer the service at home?",
      "Which area and pin code, if you'd like a home service?",
      "Is this for a special occasion like a wedding, party or festival?",
      "What date and time slot works for you?",
    ],
    defaultServices: [
      { name: "Haircut & styling (women)", priceMinPaise: 50000, priceMaxPaise: 150000, unit: "per session" },
      { name: "Facial (classic to premium)", priceMinPaise: 80000, priceMaxPaise: 300000, unit: "per session" },
      { name: "Bridal makeup package", priceMinPaise: 1500000, priceMaxPaise: 5000000, unit: "per package" },
      { name: "Party makeup", priceMinPaise: 250000, priceMaxPaise: 800000, unit: "per session" },
      { name: "Hair colour/highlights", priceMinPaise: 200000, priceMaxPaise: 800000, unit: "per session" },
    ],
    suggestedDiscountPolicy: "15% off first-time home service; festive combo offers instead of discounts on bridal packages.",
    templateStyle: "glam before/after reel",
    imageStyleNotes: "Soft glam close-ups — glowing skin, bridal makeup looks, styled hair; pastel and rose-gold palette. Clean salon interiors or elegant at-home setups, Indian skin tones front and centre.",
    aiToneNotes: "Friendly and pampering — mirror the customer's excitement for occasions, suggest combos, and confirm the slot fast since good slots fill up on weekends.",
  },
  pet_care: {
    key: "pet_care",
    displayName: "Pet Care",
    emoji: "🐾",
    description: "Grooming, boarding, walking and daycare for dogs and cats.",
    urgencyLevel: "medium",
    pricingType: "per_job",
    qualificationQuestions: [
      "What pet do you have — dog or cat — and which breed?",
      "Which service do you need — grooming, boarding, daily walking, or daycare?",
      "How old is your pet, and are vaccinations up to date?",
      "Is your pet comfortable with strangers, or anxious/aggressive around new people?",
      "Which area and pin code are you in — and do you need home pickup?",
      "For boarding: what are the drop-off and pickup dates?",
    ],
    defaultServices: [
      { name: "Dog grooming — bath, trim & nails", priceMinPaise: 80000, priceMaxPaise: 250000, unit: "per session" },
      { name: "Pet boarding", priceMinPaise: 40000, priceMaxPaise: 100000, unit: "per day" },
      { name: "Daily dog walking (monthly)", priceMinPaise: 200000, priceMaxPaise: 500000, unit: "per month" },
      { name: "Cat grooming", priceMinPaise: 70000, priceMaxPaise: 200000, unit: "per session" },
      { name: "Pet taxi / home pickup", priceMinPaise: 30000, priceMaxPaise: 80000, unit: "per trip" },
    ],
    suggestedDiscountPolicy: "10% off the first grooming session; weekly boarding priced at 6 days for 7.",
    templateStyle: "cute pet spotlight",
    imageStyleNotes: "Happy, freshly groomed pets in bright natural light; playful compositions with paw-print motifs. Real grooming shots over stock-style perfection.",
    aiToneNotes: "Affectionate and detail-oriented — use the pet's name once shared, and proactively reassure about hygiene, vaccination checks and gentle handling.",
  },
  tutoring: {
    key: "tutoring",
    displayName: "Tutoring & Coaching",
    emoji: "📚",
    description: "Home, online and centre-based tutoring for school and entrance exams.",
    urgencyLevel: "medium",
    pricingType: "subscription",
    qualificationQuestions: [
      "Which class is the student in, and which board — CBSE, ICSE or State?",
      "Which subjects do you need help with?",
      "Do you prefer home tuition, online classes, or visiting the tutor/centre?",
      "Which area and pin code are you in, if home tuition?",
      "Is there a specific exam target — boards, JEE, NEET, Olympiads — and how is the student doing currently?",
      "How many classes per week are you looking at?",
    ],
    defaultServices: [
      { name: "Class 6-8 all subjects (monthly)", priceMinPaise: 250000, priceMaxPaise: 600000, unit: "per month" },
      { name: "Class 9-10 maths & science (monthly)", priceMinPaise: 350000, priceMaxPaise: 800000, unit: "per month" },
      { name: "Class 11-12 PCM/PCB (per subject, monthly)", priceMinPaise: 400000, priceMaxPaise: 1000000, unit: "per subject per month" },
      { name: "JEE/NEET crash course", priceMinPaise: 1500000, priceMaxPaise: 4000000, unit: "per course" },
      { name: "Spoken English (monthly)", priceMinPaise: 200000, priceMaxPaise: 500000, unit: "per month" },
    ],
    suggestedDiscountPolicy: "First demo class free; 10% off on quarterly fee payment, sibling discount of 15%.",
    templateStyle: "result/rank announcement card",
    imageStyleNotes: "Clean academic layouts — student result highlights, marks improvement graphics, tutor at a whiteboard. Trustworthy blues and whites with bold percentage/rank callouts.",
    aiToneNotes: "Respectful and parent-friendly — parents are usually the decision makers, so address concerns about results and discipline, and always offer the free demo class.",
  },
  catering: {
    key: "catering",
    displayName: "Catering Services",
    emoji: "🍽️",
    description: "Wedding, party and corporate catering with customisable menus.",
    urgencyLevel: "medium",
    pricingType: "quote",
    qualificationQuestions: [
      "What's the occasion — wedding, birthday, housewarming, or corporate event — and the date?",
      "Which city and venue/locality is the event at?",
      "Roughly how many guests are you expecting?",
      "Veg, non-veg or Jain — and any cuisine preference like North Indian, South Indian or multi-cuisine?",
      "Do you want buffet or sit-down service, and any live counters like chaat or dosa?",
      "What per-plate budget are you targeting?",
    ],
    defaultServices: [
      { name: "Veg buffet", priceMinPaise: 25000, priceMaxPaise: 60000, unit: "per plate" },
      { name: "Non-veg buffet", priceMinPaise: 35000, priceMaxPaise: 90000, unit: "per plate" },
      { name: "Premium wedding menu", priceMinPaise: 80000, priceMaxPaise: 180000, unit: "per plate" },
      { name: "Live counter add-on (chaat/dosa)", priceMinPaise: 800000, priceMaxPaise: 2000000, unit: "per counter" },
      { name: "Corporate lunch boxes", priceMinPaise: 12000, priceMaxPaise: 30000, unit: "per box" },
    ],
    suggestedDiscountPolicy: "Per-plate rates negotiable above 200 guests; free tasting session for confirmed wedding enquiries.",
    templateStyle: "menu highlight grid",
    imageStyleNotes: "Overhead spreads of Indian thalis, live counters with steam and garnish close-ups; rich, saturated food photography. Banana leaf, copper serveware and festive table styling.",
    aiToneNotes: "Hospitable and flexible — lead with menu possibilities, not price. Lock guest count and date early, and offer a tasting to move serious leads forward.",
  },
  event_planning: {
    key: "event_planning",
    displayName: "Event Planning",
    emoji: "🎉",
    description: "Decor, management and full planning for weddings, parties and corporate events.",
    urgencyLevel: "medium",
    pricingType: "quote",
    qualificationQuestions: [
      "What's the event — wedding, birthday, anniversary, or corporate — and the date?",
      "Which city, and is the venue already booked?",
      "How many guests are you expecting?",
      "Do you need decor only, or full planning — vendors, catering, entertainment, the works?",
      "Any theme or reference pictures you have in mind?",
      "What overall budget band are you working with?",
    ],
    defaultServices: [
      { name: "Birthday party decor", priceMinPaise: 500000, priceMaxPaise: 2500000, unit: "per event" },
      { name: "Wedding decor package", priceMinPaise: 7500000, priceMaxPaise: 30000000, unit: "per event" },
      { name: "Corporate event management", priceMinPaise: 5000000, priceMaxPaise: 25000000, unit: "per event" },
      { name: "Full wedding planning", priceMinPaise: 15000000, priceMaxPaise: 60000000, unit: "per wedding" },
    ],
    suggestedDiscountPolicy: "Complimentary theme mock-up on bookings above ₹1L; early-bird pricing for off-season dates.",
    templateStyle: "event showcase carousel",
    imageStyleNotes: "Dramatic wide shots of mandaps, balloon arches and stage decor with fairy lights; vibrant marigold, pastel and royal themes. Show scale and detail shots together.",
    aiToneNotes: "Enthusiastic and organised — match the excitement of the occasion, gather date/venue/guest count fast, and position a free concept call as the next step.",
  },
  ac_appliance_repair: {
    key: "ac_appliance_repair",
    displayName: "AC & Appliance Repair",
    emoji: "❄️",
    description: "Repair and servicing for ACs, refrigerators, washing machines and more.",
    urgencyLevel: "high",
    pricingType: "per_job",
    qualificationQuestions: [
      "Which appliance needs attention — AC, refrigerator, washing machine, geyser — and which brand?",
      "What's the problem — not cooling, not starting, noise, or water leakage?",
      "For ACs: split or window, and how many units?",
      "How old is the appliance, and is it under warranty or AMC?",
      "Which area and pin code should the technician come to, and how soon do you need the visit?",
    ],
    defaultServices: [
      { name: "AC service (jet/wet)", priceMinPaise: 45000, priceMaxPaise: 80000, unit: "per unit" },
      { name: "AC gas refill", priceMinPaise: 180000, priceMaxPaise: 350000, unit: "per unit" },
      { name: "AC installation/uninstallation", priceMinPaise: 120000, priceMaxPaise: 250000, unit: "per unit" },
      { name: "Washing machine repair", priceMinPaise: 40000, priceMaxPaise: 200000, unit: "per job" },
      { name: "Refrigerator repair", priceMinPaise: 50000, priceMaxPaise: 250000, unit: "per job" },
    ],
    suggestedDiscountPolicy: "Visiting charge waived if repair is done; 20% off per-unit servicing for 3+ ACs.",
    templateStyle: "seasonal service reminder",
    imageStyleNotes: "Technician servicing a split AC with clean tools and covered flooring; cool blue tones for summer campaigns. Simple icon-led graphics for service checklists.",
    aiToneNotes: "Prompt and transparent — summer AC leads are extremely time-sensitive, so confirm locality and slot immediately. Be upfront that final quote follows inspection.",
  },
  pest_control: {
    key: "pest_control",
    displayName: "Pest Control",
    emoji: "🐜",
    description: "Safe, odourless pest control for homes, offices and societies.",
    urgencyLevel: "medium",
    pricingType: "per_job",
    qualificationQuestions: [
      "Which pest is the problem — cockroaches, termites, bed bugs, mosquitoes, or rodents?",
      "What's the property — 1BHK, 2BHK, 3BHK, villa or office — and approximate area?",
      "How long have you noticed the problem, and how severe is it?",
      "Do you want a one-time treatment or an annual contract (AMC)?",
      "Are there kids, elderly people or pets at home?",
      "Which area and pin code is the property in?",
    ],
    defaultServices: [
      { name: "General pest control — 1BHK", priceMinPaise: 80000, priceMaxPaise: 150000, unit: "per 1BHK" },
      { name: "General pest control — 2BHK", priceMinPaise: 100000, priceMaxPaise: 200000, unit: "per 2BHK" },
      { name: "Cockroach gel treatment", priceMinPaise: 70000, priceMaxPaise: 150000, unit: "per treatment" },
      { name: "Anti-termite treatment", priceMinPaise: 350000, priceMaxPaise: 900000, unit: "per 1,000 sq ft" },
      { name: "Bed bug treatment — 2BHK", priceMinPaise: 200000, priceMaxPaise: 450000, unit: "per 2BHK" },
    ],
    suggestedDiscountPolicy: "Free re-service within 30 days if pests return; 20% effective saving on annual contracts vs one-time visits.",
    templateStyle: "myth-buster infographic",
    imageStyleNotes: "Clean, clinical visuals — technician with sprayer in a bright home, safety icons for kid/pet-safe chemicals. Avoid gross close-ups of pests; use subtle illustrated icons instead.",
    aiToneNotes: "Reassuring and educational — address safety for kids and pets proactively, explain odourless/herbal options, and recommend AMC where infestation is recurring.",
  },
  physiotherapy: {
    key: "physiotherapy",
    displayName: "Physiotherapy",
    emoji: "🩺",
    description: "Clinic and home-visit physiotherapy for pain, injury and rehabilitation.",
    urgencyLevel: "high",
    pricingType: "per_job",
    qualificationQuestions: [
      "What's the concern — back/neck pain, knee pain, sports injury, post-surgery rehab, or neuro rehab?",
      "How long has this been troubling you, and do you have a doctor's referral or recent reports?",
      "Would you prefer home visits or coming to the clinic?",
      "Which area and pin code, if home visits?",
      "What's the patient's age and current mobility level?",
      "Which time slots work best for sessions?",
    ],
    defaultServices: [
      { name: "Home visit session", priceMinPaise: 50000, priceMaxPaise: 120000, unit: "per session" },
      { name: "Clinic session", priceMinPaise: 30000, priceMaxPaise: 80000, unit: "per session" },
      { name: "Post-surgery rehab package (12 sessions)", priceMinPaise: 600000, priceMaxPaise: 1400000, unit: "per package" },
      { name: "Back/neck pain package (10 sessions)", priceMinPaise: 450000, priceMaxPaise: 1000000, unit: "per package" },
    ],
    suggestedDiscountPolicy: "First assessment at 50% off; package rates already discounted — no further discounts on packages.",
    templateStyle: "recovery journey story",
    imageStyleNotes: "Gentle, hopeful imagery — therapist guiding an exercise at home, senior patients smiling mid-recovery. Soft greens and whites, medical credibility without hospital coldness.",
    aiToneNotes: "Empathetic and clinical — acknowledge the pain first, never promise a cure, and encourage sharing reports. Someone in pain books fast, so offer the earliest assessment slot.",
  },
  yoga_wellness: {
    key: "yoga_wellness",
    displayName: "Yoga & Wellness",
    emoji: "🧘",
    description: "Group and personal yoga, meditation and holistic wellness programs.",
    urgencyLevel: "low",
    pricingType: "subscription",
    qualificationQuestions: [
      "What's your goal — flexibility, stress relief, weight management, or therapy for issues like PCOS, thyroid or back pain?",
      "Do you prefer group classes, personal sessions at home, or online?",
      "Have you practised yoga before, and any health conditions or injuries?",
      "Which area and pin code, if you want home sessions?",
      "Do mornings or evenings work better for you?",
    ],
    defaultServices: [
      { name: "Group classes at studio (monthly)", priceMinPaise: 150000, priceMaxPaise: 350000, unit: "per month" },
      { name: "Personal yoga at home (monthly, 5 days/week)", priceMinPaise: 500000, priceMaxPaise: 1200000, unit: "per month" },
      { name: "Online group batch (monthly)", priceMinPaise: 100000, priceMaxPaise: 250000, unit: "per month" },
      { name: "Corporate wellness session", priceMinPaise: 250000, priceMaxPaise: 800000, unit: "per session" },
      { name: "Trial class", priceMinPaise: 20000, priceMaxPaise: 50000, unit: "per class" },
    ],
    suggestedDiscountPolicy: "Trial class fee adjusted on enrolment; 15% off on quarterly memberships.",
    templateStyle: "calm quote + pose visual",
    imageStyleNotes: "Serene sunrise practice shots, clean mats, plants and natural light; muted earth tones and soft gradients. Minimal text overlays with breathing-room layouts.",
    aiToneNotes: "Calm and welcoming — never body-shame or over-promise health outcomes. Gently ask about health conditions and steer beginners to the trial class.",
  },
  landscaping: {
    key: "landscaping",
    displayName: "Landscaping & Gardening",
    emoji: "🌿",
    description: "Garden design, terrace/balcony setups and ongoing maintenance.",
    urgencyLevel: "low",
    pricingType: "quote",
    qualificationQuestions: [
      "What space are we working with — villa garden, terrace, balcony, or society common area?",
      "What's the approximate area in square feet?",
      "Is this a new setup/makeover, or ongoing maintenance?",
      "Which city and locality is the property in?",
      "Is there a water point available, and how much sunlight does the space get?",
      "What budget range do you have in mind?",
    ],
    defaultServices: [
      { name: "Balcony garden setup", priceMinPaise: 500000, priceMaxPaise: 2000000, unit: "per balcony" },
      { name: "Terrace garden setup", priceMinPaise: 1500000, priceMaxPaise: 6000000, unit: "per terrace" },
      { name: "Lawn installation", priceMinPaise: 4000, priceMaxPaise: 9000, unit: "per sq ft" },
      { name: "Monthly garden maintenance", priceMinPaise: 150000, priceMaxPaise: 500000, unit: "per month" },
      { name: "Vertical garden wall", priceMinPaise: 60000, priceMaxPaise: 150000, unit: "per sq ft" },
    ],
    suggestedDiscountPolicy: "Free site visit and layout sketch for projects above ₹10,000; 10% off annual maintenance contracts.",
    templateStyle: "garden transformation timelapse",
    imageStyleNotes: "Lush green terraces and balconies against city skylines; golden-hour light on planters and vertical gardens. Before/after pairs showing bare concrete turning green.",
    aiToneNotes: "Passionate and advisory — ask about sunlight and water before promising plant choices, and offer the free site visit to convert browsers into bookings.",
  },
};

export const CATEGORY_KEYS = Object.keys(CATEGORIES) as BusinessCategory[];
