"""Follow-up outreach sequence engine — Prompt 7 Step 5 (+ lost re-engagement).

A newly captured lead who hasn't started talking gets a three-message nurture
sequence: an initial contact now, a follow-up at 24h, and a last nudge at 72h.
The three Celery task IDs are stored on ``Lead.follow_up_task_ids`` so they can
be revoked the moment the lead responds or a human takes over.

Beyond the spec, a LOST lead is re-engaged 24h and 48h later (LOST -> GREETED)
so cold leads get a second chance rather than being dropped forever.

Guarantees:
- Every outreach task self-guards on ``conversation_state`` (returns immediately
  if the lead has moved on) — belt-and-suspenders behind task revocation.
- Follow-up copy is always generated by Gemini from the tenant context, never a
  hardcoded string.
"""

import json
import logging
import uuid
from typing import Any

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.ai import FLASH_LITE_MODEL
from app.core.exceptions import AIGenerationError, ExternalAPIError
from app.db.base import with_tenant_scope
from app.db.models import ConversationState
from app.modules.conversations.delivery import deliver_message, delivery_service_for
from app.worker.celery_app import celery_app
from app.worker.db import worker_session

logger = logging.getLogger(__name__)

# (step, countdown seconds) for the standard nurture sequence.
OUTREACH_DELAYS: tuple[tuple[str, int], ...] = (
    ("initial", 0),
    ("followup_one", 86400),  # 24h
    ("followup_two", 259200),  # 72h
)
# Re-engagement for LOST leads: 24h and 48h after the drop-off.
LOST_REENGAGE_DELAYS: tuple[int, ...] = (86400, 172800)

_OUTREACH_TEMPERATURE = 0.4
_OUTREACH_MAX_TOKENS = 300

# The state a given step reaches the customer in (drives the grounded prompt).
_STEP_STAGE: dict[str, ConversationState] = {
    "initial": ConversationState.NEW,
    "followup_one": ConversationState.GREETED,
    "followup_two": ConversationState.GREETED,
    "lost_reengage": ConversationState.LOST,
}

_STEP_INSTRUCTIONS: dict[str, str] = {
    "initial": (
        "Write a short, warm first outreach message introducing how {business} can help. "
        "The customer showed interest but hasn't written yet. Invite them to share what "
        "they need. Reply with ONLY the message text."
    ),
    "followup_one": (
        "The customer hasn't replied to your first message. Write a brief, friendly check-in "
        "that gently re-offers help without any pressure. Reply with ONLY the message text."
    ),
    "followup_two": (
        "This is a final, low-pressure nudge — the customer still hasn't replied. Remind them "
        "of the value on offer and make it easy to respond. Reply with ONLY the message text."
    ),
    "lost_reengage": (
        "This customer went quiet a while ago. Write a warm re-engagement message that reminds "
        "them of the value and invites them back with one light question. "
        "Reply with ONLY the message text."
    ),
}


# ---------------------------------------------------------------------------
# Scheduling + cancellation (called from capture flows and the AI worker)
# ---------------------------------------------------------------------------


async def enqueue_outreach_sequence(
    session: AsyncSession, *, tenant_id: uuid.UUID, lead_id: uuid.UUID
) -> list[str]:
    """Schedule the initial + two follow-up tasks and record their IDs on the lead."""
    from app.worker.outreach_worker import (
        send_followup_one,
        send_followup_two,
        send_initial_contact,
    )

    tasks = {
        "initial": send_initial_contact,
        "followup_one": send_followup_one,
        "followup_two": send_followup_two,
    }
    payload = {"tenant_id": str(tenant_id), "lead_id": str(lead_id)}
    task_ids = [
        tasks[step].apply_async(args=[payload], countdown=delay).id
        for step, delay in OUTREACH_DELAYS
    ]
    await _set_task_ids(session, lead_id, task_ids)
    logger.info(
        "outreach sequence enqueued",
        extra={"tenant_id": str(tenant_id), "lead_id": str(lead_id), "count": len(task_ids)},
    )
    return task_ids


async def enqueue_lost_reengagement(
    session: AsyncSession, *, tenant_id: uuid.UUID, lead_id: uuid.UUID
) -> list[str]:
    """Schedule 24h/48h re-engagement tasks for a lead that went LOST."""
    from app.worker.outreach_worker import send_lost_reengagement

    payload = {"tenant_id": str(tenant_id), "lead_id": str(lead_id)}
    task_ids = [
        send_lost_reengagement.apply_async(args=[payload], countdown=delay).id
        for delay in LOST_REENGAGE_DELAYS
    ]
    await _set_task_ids(session, lead_id, task_ids)
    logger.info(
        "lost re-engagement enqueued",
        extra={"tenant_id": str(tenant_id), "lead_id": str(lead_id), "count": len(task_ids)},
    )
    return task_ids


async def cancel_outreach_sequence(
    session: AsyncSession, *, tenant_id: uuid.UUID, lead_id: uuid.UUID
) -> int:
    """Revoke any scheduled outreach for a lead and clear the stored IDs.

    Called when the lead responds or manual mode is activated. No-op when there
    is nothing pending, so it's safe to call on every inbound turn.
    """
    row = (
        await session.execute(
            text("SELECT follow_up_task_ids FROM leads WHERE id = :id"), {"id": lead_id}
        )
    ).first()
    if row is None:
        return 0
    task_ids = list(row[0] or [])
    if not task_ids:
        return 0
    for task_id in task_ids:
        celery_app.control.revoke(str(task_id))
    await session.execute(
        text("UPDATE leads SET follow_up_task_ids = '[]'::jsonb WHERE id = :id"), {"id": lead_id}
    )
    logger.info(
        "outreach cancelled",
        extra={"tenant_id": str(tenant_id), "lead_id": str(lead_id), "revoked": len(task_ids)},
    )
    return len(task_ids)


async def _set_task_ids(session: AsyncSession, lead_id: uuid.UUID, task_ids: list[str]) -> None:
    await session.execute(
        text("UPDATE leads SET follow_up_task_ids = cast(:ids AS jsonb) WHERE id = :id"),
        {"ids": json.dumps(task_ids), "id": lead_id},
    )


# ---------------------------------------------------------------------------
# Step execution (called by the outreach_worker Celery tasks)
# ---------------------------------------------------------------------------


async def run_outreach_step(step: str, tenant_id: uuid.UUID, lead_id: uuid.UUID) -> bool:
    """Execute one outreach step. Returns True if a message was generated+sent.

    Self-guards on ``conversation_state``: the standard steps only fire while the
    lead is NEW/GREETED; ``lost_reengage`` only fires while LOST. A lead that has
    engaged, booked, or been handed off is left alone.
    """
    from app.modules.ai.context_service import assemble_tenant_context
    from app.modules.conversations.state_machine import record_transition

    async with worker_session() as session:
        async with with_tenant_scope(session, tenant_id):
            lead = await _load_lead(session, lead_id)
            if lead is None or lead["manual_mode"]:
                return False
            state = ConversationState(lead["conversation_state"])
            if not _should_run(step, state):
                logger.info(
                    "outreach step skipped (state guard)",
                    extra={"lead_id": str(lead_id), "step": step, "state": state.value},
                )
                return False
            gemini = await _decrypt_or_none(session, tenant_id, "gemini")
            delivery_service = delivery_service_for(lead["platform"])
            delivery_cred = (
                await _decrypt_or_none(session, tenant_id, delivery_service)
                if delivery_service
                else None
            )
            await session.commit()

        if gemini is None:
            logger.warning("outreach step: no gemini credential", extra={"lead_id": str(lead_id)})
            return False
        api_key = str(gemini.fields["api_key"])
        context = await assemble_tenant_context(tenant_id, session)

        try:
            message = await generate_outreach_message(step, context, tenant_id, api_key)
        except (AIGenerationError, ExternalAPIError):
            logger.error("outreach message generation failed", extra={"lead_id": str(lead_id)})
            return False
        if not message.strip():
            return False

        async with with_tenant_scope(session, tenant_id):
            if step == "initial" and state is ConversationState.NEW:
                await record_transition(
                    session,
                    lead_id=lead_id,
                    tenant_id=tenant_id,
                    from_state=ConversationState.NEW,
                    to_state=ConversationState.GREETED,
                )
            elif step == "lost_reengage" and state is ConversationState.LOST:
                await record_transition(
                    session,
                    lead_id=lead_id,
                    tenant_id=tenant_id,
                    from_state=ConversationState.LOST,
                    to_state=ConversationState.GREETED,
                )
            await _save_assistant_message(session, tenant_id, lead_id, message)
            await session.commit()

        delivered = await deliver_message(
            platform=lead["platform"],
            platform_id=lead["platform_id"],
            text=message,
            credential=delivery_cred,
            lead_id=lead_id,
            tenant_id=tenant_id,
            last_inbound_at=lead["last_inbound_at"],
        )
        _emit_new_message(tenant_id, lead_id, message)
        if not delivered:
            logger.warning(
                "outreach message not delivered",
                extra={"lead_id": str(lead_id), "platform": lead["platform"]},
            )
        return delivered


async def generate_outreach_message(
    step: str,
    context: Any,  # noqa: ANN401 — TenantAIContext (imported lazily to keep this module light)
    tenant_id: uuid.UUID,
    api_key: str,
) -> str:
    """Generate grounded outreach copy for one step — never a hardcoded string."""
    from app.modules.ai.langfuse_client import traced_ai_call
    from app.modules.ai.system_prompt_builder import build_system_prompt

    stage = _STEP_STAGE.get(step, ConversationState.GREETED)
    system = build_system_prompt(context, stage)
    instruction = _STEP_INSTRUCTIONS[step].format(business=context.business_name)
    result = await traced_ai_call(
        api_key=api_key,
        system=system,
        user_message=instruction,
        model=FLASH_LITE_MODEL,
        call_type=f"outreach-{step}",
        tenant_id=tenant_id,
        temperature=_OUTREACH_TEMPERATURE,
        max_tokens=_OUTREACH_MAX_TOKENS,
    )
    return result.text.strip()


def _should_run(step: str, state: ConversationState) -> bool:
    if step == "lost_reengage":
        return state is ConversationState.LOST
    return state in (ConversationState.NEW, ConversationState.GREETED)


async def _load_lead(session: Any, lead_id: uuid.UUID) -> dict[str, Any] | None:  # noqa: ANN401
    row = (
        await session.execute(
            text(
                "SELECT conversation_state, manual_mode, platform, platform_id, last_inbound_at "
                "FROM leads WHERE id = :id"
            ),
            {"id": lead_id},
        )
    ).first()
    if row is None:
        return None
    return {
        "conversation_state": str(row[0]),
        "manual_mode": bool(row[1]),
        "platform": str(row[2]),
        "platform_id": str(row[3]),
        "last_inbound_at": row[4],
    }


async def _decrypt_or_none(session: Any, tenant_id: uuid.UUID, service: str) -> Any | None:  # noqa: ANN401
    from app.core.exceptions import CredentialVerificationError
    from app.modules.credentials.service import get_decrypted_credential

    try:
        return await get_decrypted_credential(tenant_id, service, session)
    except CredentialVerificationError:
        return None


async def _save_assistant_message(
    session: Any,  # noqa: ANN401
    tenant_id: uuid.UUID,
    lead_id: uuid.UUID,
    content: str,
) -> None:
    await session.execute(
        text(
            "INSERT INTO conversations (tenant_id, lead_id, role, content) "
            "VALUES (:tid, :lid, 'assistant', :content)"
        ),
        {"tid": tenant_id, "lid": lead_id, "content": content},
    )


def _emit_new_message(tenant_id: uuid.UUID, lead_id: uuid.UUID, message: str) -> None:
    from app.modules.realtime.events import EventEmitter

    EventEmitter.emit_sync(
        tenant_id, "new_message", {"lead_id": str(lead_id), "role": "assistant", "content": message}
    )
