"""onboarding_and_brandkit

Revision ID: 2565fc452a39
Revises: c3e5a7b9d1f2
Create Date: 2026-07-10 03:03:52.360276
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "2565fc452a39"
down_revision: str | None = "c3e5a7b9d1f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_token", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_onboarding_events_token",
        "onboarding_events",
        ["session_token", "created_at"],
        unique=False,
    )
    op.create_table(
        "onboarding_sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_token", sa.String(length=64), nullable=False),
        sa.Column("current_stage", sa.String(length=32), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_token"),
    )
    op.add_column("brand_kits", sa.Column("logo_r2_key", sa.String(length=512), nullable=True))
    op.add_column("brand_kits", sa.Column("nanobanana_style_prompt", sa.Text(), nullable=True))
    # NOTE: autogenerate wanted to drop the hand-written performance indexes
    # (ix_posts_scheduled_at_pending, ix_leads_tenant_last_inbound,
    # ix_conversations_lead_created, ix_business_profiles_services_gin) and
    # uq_users_email_global because they exist only in SQL migrations, not in
    # model metadata. Those drops were REMOVED by hand — do not re-add them.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("brand_kits", "nanobanana_style_prompt")
    op.drop_column("brand_kits", "logo_r2_key")
    op.drop_table("onboarding_sessions")
    op.drop_index("ix_onboarding_events_token", table_name="onboarding_events")
    op.drop_table("onboarding_events")
    # ### end Alembic commands ###
