/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing.index'
import { Route as MarketingTermsRouteImport } from './routes/_marketing.terms'
import { Route as MarketingRegisterRouteImport } from './routes/_marketing.register'
import { Route as MarketingPrivacyRouteImport } from './routes/_marketing.privacy'
import { Route as MarketingPricingRouteImport } from './routes/_marketing.pricing'
import { Route as MarketingHelpRouteImport } from './routes/_marketing.help'
import { Route as MarketingFeaturesRouteImport } from './routes/_marketing.features'
import { Route as MarketingFaqRouteImport } from './routes/_marketing.faq'
import { Route as MarketingDemoRouteImport } from './routes/_marketing.demo'
import { Route as MarketingBlogRouteImport } from './routes/_marketing.blog'
import { Route as MarketingAboutRouteImport } from './routes/_marketing.about'
import { Route as MarketingSolutionsIndexRouteImport } from './routes/_marketing.solutions.index'
import { Route as MarketingSolutionsCategoryRouteImport } from './routes/_marketing.solutions.$category'
import { Route as MarketingBlogSlugRouteImport } from './routes/_marketing.blog.$slug'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTermsRoute = MarketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingRegisterRoute = MarketingRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacyRoute = MarketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingHelpRoute = MarketingHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesRoute = MarketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFaqRoute = MarketingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingDemoRoute = MarketingDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogRoute = MarketingBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSolutionsIndexRoute = MarketingSolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSolutionsCategoryRoute =
  MarketingSolutionsCategoryRouteImport.update({
    id: '/solutions/$category',
    path: '/solutions/$category',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingBlogSlugRoute = MarketingBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketingBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/about': typeof MarketingAboutRoute
  '/blog': typeof MarketingBlogRouteWithChildren
  '/demo': typeof MarketingDemoRoute
  '/faq': typeof MarketingFaqRoute
  '/features': typeof MarketingFeaturesRoute
  '/help': typeof MarketingHelpRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/register': typeof MarketingRegisterRoute
  '/terms': typeof MarketingTermsRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/solutions/$category': typeof MarketingSolutionsCategoryRoute
  '/solutions/': typeof MarketingSolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof MarketingAboutRoute
  '/blog': typeof MarketingBlogRouteWithChildren
  '/demo': typeof MarketingDemoRoute
  '/faq': typeof MarketingFaqRoute
  '/features': typeof MarketingFeaturesRoute
  '/help': typeof MarketingHelpRoute
  '/pricing': typeof MarketingPricingRoute
  '/privacy': typeof MarketingPrivacyRoute
  '/register': typeof MarketingRegisterRoute
  '/terms': typeof MarketingTermsRoute
  '/': typeof MarketingIndexRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/solutions/$category': typeof MarketingSolutionsCategoryRoute
  '/solutions': typeof MarketingSolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/blog': typeof MarketingBlogRouteWithChildren
  '/_marketing/demo': typeof MarketingDemoRoute
  '/_marketing/faq': typeof MarketingFaqRoute
  '/_marketing/features': typeof MarketingFeaturesRoute
  '/_marketing/help': typeof MarketingHelpRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/privacy': typeof MarketingPrivacyRoute
  '/_marketing/register': typeof MarketingRegisterRoute
  '/_marketing/terms': typeof MarketingTermsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/blog/$slug': typeof MarketingBlogSlugRoute
  '/_marketing/solutions/$category': typeof MarketingSolutionsCategoryRoute
  '/_marketing/solutions/': typeof MarketingSolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/demo'
    | '/faq'
    | '/features'
    | '/help'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/blog/$slug'
    | '/solutions/$category'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/blog'
    | '/demo'
    | '/faq'
    | '/features'
    | '/help'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/'
    | '/blog/$slug'
    | '/solutions/$category'
    | '/solutions'
  id:
    | '__root__'
    | '/_marketing'
    | '/_marketing/about'
    | '/_marketing/blog'
    | '/_marketing/demo'
    | '/_marketing/faq'
    | '/_marketing/features'
    | '/_marketing/help'
    | '/_marketing/pricing'
    | '/_marketing/privacy'
    | '/_marketing/register'
    | '/_marketing/terms'
    | '/_marketing/'
    | '/_marketing/blog/$slug'
    | '/_marketing/solutions/$category'
    | '/_marketing/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/terms': {
      id: '/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MarketingTermsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/register': {
      id: '/_marketing/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof MarketingRegisterRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacy': {
      id: '/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MarketingPrivacyRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/help': {
      id: '/_marketing/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof MarketingHelpRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features': {
      id: '/_marketing/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof MarketingFeaturesRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/faq': {
      id: '/_marketing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof MarketingFaqRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/demo': {
      id: '/_marketing/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof MarketingDemoRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog': {
      id: '/_marketing/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof MarketingBlogRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/solutions/': {
      id: '/_marketing/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof MarketingSolutionsIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/solutions/$category': {
      id: '/_marketing/solutions/$category'
      path: '/solutions/$category'
      fullPath: '/solutions/$category'
      preLoaderRoute: typeof MarketingSolutionsCategoryRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog/$slug': {
      id: '/_marketing/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof MarketingBlogSlugRouteImport
      parentRoute: typeof MarketingBlogRoute
    }
  }
}

interface MarketingBlogRouteChildren {
  MarketingBlogSlugRoute: typeof MarketingBlogSlugRoute
}

const MarketingBlogRouteChildren: MarketingBlogRouteChildren = {
  MarketingBlogSlugRoute: MarketingBlogSlugRoute,
}

const MarketingBlogRouteWithChildren = MarketingBlogRoute._addFileChildren(
  MarketingBlogRouteChildren,
)

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingBlogRoute: typeof MarketingBlogRouteWithChildren
  MarketingDemoRoute: typeof MarketingDemoRoute
  MarketingFaqRoute: typeof MarketingFaqRoute
  MarketingFeaturesRoute: typeof MarketingFeaturesRoute
  MarketingHelpRoute: typeof MarketingHelpRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingPrivacyRoute: typeof MarketingPrivacyRoute
  MarketingRegisterRoute: typeof MarketingRegisterRoute
  MarketingTermsRoute: typeof MarketingTermsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingSolutionsCategoryRoute: typeof MarketingSolutionsCategoryRoute
  MarketingSolutionsIndexRoute: typeof MarketingSolutionsIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingBlogRoute: MarketingBlogRouteWithChildren,
  MarketingDemoRoute: MarketingDemoRoute,
  MarketingFaqRoute: MarketingFaqRoute,
  MarketingFeaturesRoute: MarketingFeaturesRoute,
  MarketingHelpRoute: MarketingHelpRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingPrivacyRoute: MarketingPrivacyRoute,
  MarketingRegisterRoute: MarketingRegisterRoute,
  MarketingTermsRoute: MarketingTermsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingSolutionsCategoryRoute: MarketingSolutionsCategoryRoute,
  MarketingSolutionsIndexRoute: MarketingSolutionsIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
